USE [master]
GO

/****** Object:  Database [BigEChatBot]    Script Date: 5/8/2026 7:24:34 AM ******/
CREATE DATABASE [BigEChatBot]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BigEChatBot', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BigEChatBot.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BigEChatBot_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BigEChatBot_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BigEChatBot].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BigEChatBot] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BigEChatBot] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BigEChatBot] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BigEChatBot] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BigEChatBot] SET ARITHABORT OFF 
GO

ALTER DATABASE [BigEChatBot] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BigEChatBot] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BigEChatBot] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BigEChatBot] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BigEChatBot] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BigEChatBot] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BigEChatBot] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BigEChatBot] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BigEChatBot] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BigEChatBot] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BigEChatBot] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BigEChatBot] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BigEChatBot] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BigEChatBot] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BigEChatBot] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BigEChatBot] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BigEChatBot] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BigEChatBot] SET RECOVERY FULL 
GO

ALTER DATABASE [BigEChatBot] SET  MULTI_USER 
GO

ALTER DATABASE [BigEChatBot] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BigEChatBot] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BigEChatBot] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BigEChatBot] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BigEChatBot] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BigEChatBot] SET  READ_WRITE 
GO

